services:
    _defaults:
        public: true # Controllers need to be public
        autowire: true
        tags:
            - 'controller.service_arguments'
        bind:
            $entityManager: '@doctrine.orm.entity_manager'

    Kematjaya\VisitorTrackingBundle\Controller\:
        resource: '../../Controller/*'
