services:
    _defaults:
        public: true
        autowire: true
        
    Kematjaya\VisitorTrackingBundle\Controller\DeviceController:
        class: Kematjaya\VisitorTrackingBundle\Controller\DeviceController
        calls: 
            - setContainer: ['@service_container']
      
    visitor.security.firewall.map:
        alias: security.firewall.map
        public: true
        
    Kematjaya\VisitorTrackingBundle\EventListener\VisitorTrackingSubscriber:
        tags:
            - { name: kernel.event_subscriber }
            
    Kematjaya\VisitorTrackingBundle\Repository\VisitorTrackingRepositoryInterface:
        class: Kematjaya\VisitorTrackingBundle\Repository\VisitorTrackingRepository

    Kematjaya\VisitorTrackingBundle\Manager\DeviceFingerprintManager:

    Kematjaya\VisitorTrackingBundle\Storage\SessionStore:
        
    Kematjaya\VisitorTrackingBundle\Twig\DeviceExtension:
        class: Kematjaya\VisitorTrackingBundle\Twig\DeviceExtension
        tags: ['twig.extension']
