imports:
    - { resource: 'controllers.yml' }

services:
    _defaults:
        public: false
        autowire: true
        
    Kematjaya\VisitorTrackingBundle\EventListener\VisitorTrackingSubscriber:
        arguments:
            $entityManager: "@doctrine.orm.entity_manager"
            $firewallBlacklist: [] # Firewall blacklist, populated from config.
            $firewallMap: "@security.firewall.map"
        tags:
            - { name: kernel.event_subscriber }

    Kematjaya\VisitorTrackingBundle\Manager\DeviceFingerprintManager:

    Kematjaya\VisitorTrackingBundle\Storage\SessionStore:
