services:
    _defaults:
        public: true
        autowire: true
        
    Kematjaya\VisitorTrackingBundle\Controller\DeviceController:
        class: Kematjaya\VisitorTrackingBundle\Controller\DeviceController
        calls: 
            - setContainer: ['@service_container']
            
    Kematjaya\VisitorTrackingBundle\EventListener\VisitorTrackingSubscriber:
        arguments:
            $entityManager: "@doctrine.orm.entity_manager"
            $firewallBlacklist: [] # Firewall blacklist, populated from config.
            $firewallMap: "@security.firewall.map"
        tags:
            - { name: kernel.event_subscriber }
            
    Kematjaya\VisitorTrackingBundle\Repository\VisitorTrackingRepositoryInterface:
        class: Kematjaya\VisitorTrackingBundle\Repository\VisitorTrackingRepository

    Kematjaya\VisitorTrackingBundle\Manager\DeviceFingerprintManager:

    Kematjaya\VisitorTrackingBundle\Storage\SessionStore:
